# Generated by Django 4.1 on 2022-08-28 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=128)),
                ('notes', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Collection_Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Local_Government',
            fields=[
                ('local_government_area', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScraper.collection_year')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('parcels_address', models.CharField(max_length=128)),
                ('formatted_address', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=128)),
                ('menu', models.BooleanField(default=False)),
                ('opening_hours', models.JSONField()),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScraper.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='local_government_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScraper.local_government'),
        ),
    ]
