# Generated by Django 4.1 on 2022-08-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='category_one',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='category_three',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='category_two',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='sub_cat_three',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='sub_cat_two',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='sub_cat_one',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
