# Generated by Django 4.1 on 2022-08-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0003_alter_business_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_details',
            old_name='parcels_address',
            new_name='parcel_address',
        ),
    ]
