# Generated by Django 4.1 on 2022-09-24 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=128)),
                ('google_id', models.CharField(default=' ', max_length=128, null=True)),
                ('notes', models.TextField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection_Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Local_Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_government_area', models.CharField(max_length=128)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScraper.collection_year')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=15, default=0.0, max_digits=18, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, default=0.0, max_digits=18, null=True)),
                ('parcel_address', models.CharField(default='', max_length=128, null=True)),
                ('formatted_address', models.CharField(default='', max_length=128, null=True)),
                ('phone', models.CharField(default='', max_length=15, null=True)),
                ('website', models.CharField(default='', max_length=128, null=True)),
                ('menu', models.BooleanField(default=False, null=True)),
                ('opening_hours', models.JSONField(default=dict, null=True)),
                ('business_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webScraper.business')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_classifications', models.CharField(default='None', max_length=128, null=True)),
                ('classification', models.CharField(choices=[('A', 'Food Retail'), ('B', 'Food Service'), ('C', 'Charitable Food Provisions'), ('D', 'Food Productiond and Preperation'), ('E', 'Institutional Food'), ('F', 'Accomadation and Recreation')], default='None', max_length=1, null=True)),
                ('possible_categories', models.CharField(default='None', max_length=128, null=True)),
                ('category_one', models.CharField(choices=[('1.0', 'Supermarket/Grocery Store'), ('2.0', 'Convenience Store'), ('3.0', 'World/Ethnic Foods'), ('4.0', 'Health Food Store'), ('5.0', 'Butcher/Poultry Store'), ('6.0', 'Fishmonger'), ('7.0', 'Bakery'), ('8.0', 'Fruit and Veg / Greengrocer'), ('9.0', 'Delicatessen'), ('10.0', 'Pastry/Patisserie Store'), ('11.0', 'Confectionary/Chocolate/Ice-Cream'), ('12.0', 'Not otherwise specified'), ('13.0', 'Liquor/Bottle Shop'), ('14.0', 'General Retail')], default='None', max_length=5, null=True)),
                ('sub_cat_one', models.CharField(default='None', max_length=128, null=True)),
                ('business_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webScraper.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='local_government_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScraper.local_government'),
        ),
    ]
