# Generated by Django 4.1 on 2022-10-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='phone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
