# Generated by Django 4.1 on 2022-09-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_business_types',
            field=models.CharField(default=' ', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=115.8612164, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=-31.9524993, max_digits=10, null=True),
        ),
    ]
