# Generated by Django 4.1 on 2022-09-28 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0002_business_google_business_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_government_area', models.CharField(max_length=128)),
                ('business_name', models.CharField(max_length=128)),
                ('classification', models.CharField(default='None', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classification_count', models.IntegerField(default=0)),
                ('Category_one_count', models.IntegerField(default=0)),
                ('Sub_one_count', models.IntegerField(default=0)),
                ('local_government_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScraper.local_government')),
            ],
        ),
    ]
