# Generated by Django 4.1 on 2022-10-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0003_business_classification_class_statistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_statistic',
            old_name='Category_one_count',
            new_name='classifications_count',
        ),
        migrations.RemoveField(
            model_name='class_statistic',
            name='Classification_count',
        ),
        migrations.RemoveField(
            model_name='class_statistic',
            name='Sub_one_count',
        ),
        migrations.AddField(
            model_name='class_statistic',
            name='classifications',
            field=models.CharField(default='None', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='P_Class_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_classifications', models.CharField(default='None', max_length=128, null=True)),
                ('P_classification_count', models.IntegerField(default=0)),
                ('local_government_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScraper.local_government')),
            ],
        ),
        migrations.CreateModel(
            name='P_Category_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_categories', models.CharField(default='None', max_length=128, null=True)),
                ('P_categories_count', models.IntegerField(default=0)),
                ('local_government_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScraper.local_government')),
            ],
        ),
        migrations.CreateModel(
            name='Category_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(default='None', max_length=128, null=True)),
                ('categories_count', models.IntegerField(default=0)),
                ('local_government_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScraper.local_government')),
            ],
        ),
    ]
