# Generated by Django 4.1 on 2022-10-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0003_alter_contact_details_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='opening_hours',
            field=models.JSONField(default=[''], null=True),
        ),
    ]
