# Generated by Django 4.1 on 2022-10-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0004_rename_category_one_count_class_statistic_classifications_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_statistic',
            name='local_government_area',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='class_statistic',
            name='local_government_area',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='p_category_statistic',
            name='local_government_area',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='p_class_statistic',
            name='local_government_area',
            field=models.CharField(max_length=128),
        ),
    ]
