# Generated by Django 4.1 on 2022-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0005_alter_category_statistic_local_government_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_government',
            name='food_retail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='local_government',
            name='food_service',
            field=models.IntegerField(default=0),
        ),
    ]
