# Generated by Django 4.1 on 2022-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webScraper', '0006_local_government_food_retail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business_classification',
        ),
        migrations.DeleteModel(
            name='Category_statistic',
        ),
        migrations.DeleteModel(
            name='Class_statistic',
        ),
        migrations.DeleteModel(
            name='P_Category_statistic',
        ),
        migrations.DeleteModel(
            name='P_Class_statistic',
        ),
        migrations.AddField(
            model_name='local_government',
            name='ACCOMMODATION_RECREATION_SERVICES',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='local_government',
            name='CHARITABLE_FOOD_PROVISION',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='local_government',
            name='FOOD_PRODUCTION_AND_PREPARATION',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='local_government',
            name='INSTITUTIONAL_FOOD',
            field=models.IntegerField(default=0),
        ),
    ]
